package com.files;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArInternalMetadata generated by hbm2java
 */
@Entity
@Table(name = "ar_internal_metadata", schema = "public")
public class ArInternalMetadata implements java.io.Serializable {

	private String key;
	private String value;
	private Date createdAt;
	private Date updatedAt;

	public ArInternalMetadata() {
	}

	public ArInternalMetadata(String key, Date createdAt, Date updatedAt) {
		this.key = key;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ArInternalMetadata(String key, String value, Date createdAt, Date updatedAt) {
		this.key = key;
		this.value = value;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "key", unique = true, nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
