package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdminNotifications generated by hbm2java
 */
@Entity
@Table(name = "admin_notifications", schema = "public")
public class AdminNotifications implements java.io.Serializable {

	private long id;
	private Long userId;
	private Long retailerId;
	private Long orderId;
	private String data;
	private Boolean actionTaken;
	private Date createdAt;
	private Date updatedAt;

	public AdminNotifications() {
	}

	public AdminNotifications(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public AdminNotifications(long id, Long userId, Long retailerId, Long orderId, String data, Boolean actionTaken,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.userId = userId;
		this.retailerId = retailerId;
		this.orderId = orderId;
		this.data = data;
		this.actionTaken = actionTaken;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "retailer_id")
	public Long getRetailerId() {
		return this.retailerId;
	}

	public void setRetailerId(Long retailerId) {
		this.retailerId = retailerId;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "data")
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "action_taken")
	public Boolean getActionTaken() {
		return this.actionTaken;
	}

	public void setActionTaken(Boolean actionTaken) {
		this.actionTaken = actionTaken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
