package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AdminUsers generated by hbm2java
 */
@Entity
@Table(name = "admin_users", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "emp_id"), @UniqueConstraint(columnNames = "phone_number"),
		@UniqueConstraint(columnNames = "reset_password_token") })
public class AdminUsers implements java.io.Serializable {

	private long id;
	private String name;
	private String email;
	private String empId;
	private String phoneNumber;
	private long roleId;
	private String encryptedPassword;
	private Date deletedAt;
	private Boolean pswdChanged;
	private String resetPasswordToken;
	private Date resetPasswordSentAt;
	private Date rememberCreatedAt;
	private int signInCount;
	private Date currentSignInAt;
	private Date lastSignInAt;
	private Serializable currentSignInIp;
	private Serializable lastSignInIp;
	private Date createdAt;
	private Date updatedAt;
	private String otpSecretKey;

	public AdminUsers() {
	}

	public AdminUsers(long id, String name, String email, String empId, String phoneNumber, long roleId,
			String encryptedPassword, int signInCount, Date createdAt, Date updatedAt) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.empId = empId;
		this.phoneNumber = phoneNumber;
		this.roleId = roleId;
		this.encryptedPassword = encryptedPassword;
		this.signInCount = signInCount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public AdminUsers(long id, String name, String email, String empId, String phoneNumber, long roleId,
			String encryptedPassword, Date deletedAt, Boolean pswdChanged, String resetPasswordToken,
			Date resetPasswordSentAt, Date rememberCreatedAt, int signInCount, Date currentSignInAt, Date lastSignInAt,
			Serializable currentSignInIp, Serializable lastSignInIp, Date createdAt, Date updatedAt,
			String otpSecretKey) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.empId = empId;
		this.phoneNumber = phoneNumber;
		this.roleId = roleId;
		this.encryptedPassword = encryptedPassword;
		this.deletedAt = deletedAt;
		this.pswdChanged = pswdChanged;
		this.resetPasswordToken = resetPasswordToken;
		this.resetPasswordSentAt = resetPasswordSentAt;
		this.rememberCreatedAt = rememberCreatedAt;
		this.signInCount = signInCount;
		this.currentSignInAt = currentSignInAt;
		this.lastSignInAt = lastSignInAt;
		this.currentSignInIp = currentSignInIp;
		this.lastSignInIp = lastSignInIp;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.otpSecretKey = otpSecretKey;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "emp_id", unique = true, nullable = false)
	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@Column(name = "phone_number", unique = true, nullable = false)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "role_id", nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "encrypted_password", nullable = false)
	public String getEncryptedPassword() {
		return this.encryptedPassword;
	}

	public void setEncryptedPassword(String encryptedPassword) {
		this.encryptedPassword = encryptedPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Column(name = "pswd_changed")
	public Boolean getPswdChanged() {
		return this.pswdChanged;
	}

	public void setPswdChanged(Boolean pswdChanged) {
		this.pswdChanged = pswdChanged;
	}

	@Column(name = "reset_password_token", unique = true)
	public String getResetPasswordToken() {
		return this.resetPasswordToken;
	}

	public void setResetPasswordToken(String resetPasswordToken) {
		this.resetPasswordToken = resetPasswordToken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reset_password_sent_at", length = 29)
	public Date getResetPasswordSentAt() {
		return this.resetPasswordSentAt;
	}

	public void setResetPasswordSentAt(Date resetPasswordSentAt) {
		this.resetPasswordSentAt = resetPasswordSentAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "remember_created_at", length = 29)
	public Date getRememberCreatedAt() {
		return this.rememberCreatedAt;
	}

	public void setRememberCreatedAt(Date rememberCreatedAt) {
		this.rememberCreatedAt = rememberCreatedAt;
	}

	@Column(name = "sign_in_count", nullable = false)
	public int getSignInCount() {
		return this.signInCount;
	}

	public void setSignInCount(int signInCount) {
		this.signInCount = signInCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "current_sign_in_at", length = 29)
	public Date getCurrentSignInAt() {
		return this.currentSignInAt;
	}

	public void setCurrentSignInAt(Date currentSignInAt) {
		this.currentSignInAt = currentSignInAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_sign_in_at", length = 29)
	public Date getLastSignInAt() {
		return this.lastSignInAt;
	}

	public void setLastSignInAt(Date lastSignInAt) {
		this.lastSignInAt = lastSignInAt;
	}

	@Column(name = "current_sign_in_ip")
	public Serializable getCurrentSignInIp() {
		return this.currentSignInIp;
	}

	public void setCurrentSignInIp(Serializable currentSignInIp) {
		this.currentSignInIp = currentSignInIp;
	}

	@Column(name = "last_sign_in_ip")
	public Serializable getLastSignInIp() {
		return this.lastSignInIp;
	}

	public void setLastSignInIp(Serializable lastSignInIp) {
		this.lastSignInIp = lastSignInIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "otp_secret_key")
	public String getOtpSecretKey() {
		return this.otpSecretKey;
	}

	public void setOtpSecretKey(String otpSecretKey) {
		this.otpSecretKey = otpSecretKey;
	}

}
