package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BankAddresses generated by hbm2java
 */
@Entity
@Table(name = "bank_addresses", schema = "public")
public class BankAddresses implements java.io.Serializable {

	private long id;
	private String address;
	private Double latitude;
	private Double longitude;
	private Integer bankName;
	private Integer bankType;
	private Date createdAt;
	private Date updatedAt;

	public BankAddresses() {
	}

	public BankAddresses(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public BankAddresses(long id, String address, Double latitude, Double longitude, Integer bankName, Integer bankType,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.address = address;
		this.latitude = latitude;
		this.longitude = longitude;
		this.bankName = bankName;
		this.bankType = bankType;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "bank_name")
	public Integer getBankName() {
		return this.bankName;
	}

	public void setBankName(Integer bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_type")
	public Integer getBankType() {
		return this.bankType;
	}

	public void setBankType(Integer bankType) {
		this.bankType = bankType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
