package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BankDetails generated by hbm2java
 */
@Entity
@Table(name = "bank_details", schema = "public")
public class BankDetails implements java.io.Serializable {

	private long id;
	private Merchants merchants;
	private String nameActHolder;
	private String ifsc;
	private String accountNumber;
	private Date createdAt;
	private Date updatedAt;
	private Boolean pennyValidated;
	private Boolean active;

	public BankDetails() {
	}

	public BankDetails(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public BankDetails(long id, Merchants merchants, String nameActHolder, String ifsc, String accountNumber,
			Date createdAt, Date updatedAt, Boolean pennyValidated, Boolean active) {
		this.id = id;
		this.merchants = merchants;
		this.nameActHolder = nameActHolder;
		this.ifsc = ifsc;
		this.accountNumber = accountNumber;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.pennyValidated = pennyValidated;
		this.active = active;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_id")
	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	@Column(name = "name_act_holder")
	public String getNameActHolder() {
		return this.nameActHolder;
	}

	public void setNameActHolder(String nameActHolder) {
		this.nameActHolder = nameActHolder;
	}

	@Column(name = "ifsc")
	public String getIfsc() {
		return this.ifsc;
	}

	public void setIfsc(String ifsc) {
		this.ifsc = ifsc;
	}

	@Column(name = "account_number")
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "penny_validated")
	public Boolean getPennyValidated() {
		return this.pennyValidated;
	}

	public void setPennyValidated(Boolean pennyValidated) {
		this.pennyValidated = pennyValidated;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
