package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BrandsSubCategories generated by hbm2java
 */
@Entity
@Table(name = "brands_sub_categories", schema = "public")
public class BrandsSubCategories implements java.io.Serializable {

	private long id;
	private Brands brands;
	private SubCategories subCategories;

	public BrandsSubCategories() {
	}

	public BrandsSubCategories(long id) {
		this.id = id;
	}

	public BrandsSubCategories(long id, Brands brands, SubCategories subCategories) {
		this.id = id;
		this.brands = brands;
		this.subCategories = subCategories;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brand_id")
	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sub_category_id")
	public SubCategories getSubCategories() {
		return this.subCategories;
	}

	public void setSubCategories(SubCategories subCategories) {
		this.subCategories = subCategories;
	}

}
