package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChangeLogs generated by hbm2java
 */
@Entity
@Table(name = "change_logs", schema = "public")
public class ChangeLogs implements java.io.Serializable {

	private long id;
	private String columnName;
	private Serializable objectChange;
	private Integer status;
	private Integer changedBy;
	private Integer loggableId;
	private String loggableType;
	private Date deletedAt;
	private Date createdAt;
	private Date updatedAt;

	public ChangeLogs() {
	}

	public ChangeLogs(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ChangeLogs(long id, String columnName, Serializable objectChange, Integer status, Integer changedBy,
			Integer loggableId, String loggableType, Date deletedAt, Date createdAt, Date updatedAt) {
		this.id = id;
		this.columnName = columnName;
		this.objectChange = objectChange;
		this.status = status;
		this.changedBy = changedBy;
		this.loggableId = loggableId;
		this.loggableType = loggableType;
		this.deletedAt = deletedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "column_name")
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "object_change")
	public Serializable getObjectChange() {
		return this.objectChange;
	}

	public void setObjectChange(Serializable objectChange) {
		this.objectChange = objectChange;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "changed_by")
	public Integer getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(Integer changedBy) {
		this.changedBy = changedBy;
	}

	@Column(name = "loggable_id")
	public Integer getLoggableId() {
		return this.loggableId;
	}

	public void setLoggableId(Integer loggableId) {
		this.loggableId = loggableId;
	}

	@Column(name = "loggable_type")
	public String getLoggableType() {
		return this.loggableType;
	}

	public void setLoggableType(String loggableType) {
		this.loggableType = loggableType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
