package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClubbedOrders generated by hbm2java
 */
@Entity
@Table(name = "clubbed_orders", schema = "public")
public class ClubbedOrders implements java.io.Serializable {

	private long id;
	private Long orderId;
	private Integer parentOrderId;
	private Long shopId;
	private Double latitude;
	private Double longitude;
	private Integer deliverySlot;
	private Date deliveryDate;
	private Integer orderNumber;
	private String status;
	private Date createdAt;
	private Date updatedAt;

	public ClubbedOrders() {
	}

	public ClubbedOrders(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ClubbedOrders(long id, Long orderId, Integer parentOrderId, Long shopId, Double latitude, Double longitude,
			Integer deliverySlot, Date deliveryDate, Integer orderNumber, String status, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.orderId = orderId;
		this.parentOrderId = parentOrderId;
		this.shopId = shopId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.deliverySlot = deliverySlot;
		this.deliveryDate = deliveryDate;
		this.orderNumber = orderNumber;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "parent_order_id")
	public Integer getParentOrderId() {
		return this.parentOrderId;
	}

	public void setParentOrderId(Integer parentOrderId) {
		this.parentOrderId = parentOrderId;
	}

	@Column(name = "shop_id")
	public Long getShopId() {
		return this.shopId;
	}

	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "delivery_slot")
	public Integer getDeliverySlot() {
		return this.deliverySlot;
	}

	public void setDeliverySlot(Integer deliverySlot) {
		this.deliverySlot = deliverySlot;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delivery_date", length = 13)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Column(name = "order_number")
	public Integer getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
