package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CokeOrders generated by hbm2java
 */
@Entity
@Table(name = "coke_orders", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "order_id"))
public class CokeOrders implements java.io.Serializable {

	private long id;
	private Integer retailerId;
	private String orderId;
	private Serializable orderDetails;
	private Double longitude;
	private Double latitude;
	private String shopName;
	private Date createdAt;
	private Date updatedAt;
	private Double amount;
	private Integer status;

	public CokeOrders() {
	}

	public CokeOrders(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public CokeOrders(long id, Integer retailerId, String orderId, Serializable orderDetails, Double longitude,
			Double latitude, String shopName, Date createdAt, Date updatedAt, Double amount, Integer status) {
		this.id = id;
		this.retailerId = retailerId;
		this.orderId = orderId;
		this.orderDetails = orderDetails;
		this.longitude = longitude;
		this.latitude = latitude;
		this.shopName = shopName;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.amount = amount;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "retailer_id")
	public Integer getRetailerId() {
		return this.retailerId;
	}

	public void setRetailerId(Integer retailerId) {
		this.retailerId = retailerId;
	}

	@Column(name = "order_id", unique = true)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_details")
	public Serializable getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Serializable orderDetails) {
		this.orderDetails = orderDetails;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "shop_name")
	public String getShopName() {
		return this.shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "amount", precision = 17, scale = 17)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
