package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CoupCategories generated by hbm2java
 */
@Entity
@Table(name = "coup_categories", schema = "public")
public class CoupCategories implements java.io.Serializable {

	private long id;
	private String name;
	private String imageUrl;
	private String couponCount;
	private Date createdAt;
	private Date updatedAt;
	private Set<CouponCoupCategories> couponCoupCategorieses = new HashSet<CouponCoupCategories>(0);

	public CoupCategories() {
	}

	public CoupCategories(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public CoupCategories(long id, String name, String imageUrl, String couponCount, Date createdAt, Date updatedAt,
			Set<CouponCoupCategories> couponCoupCategorieses) {
		this.id = id;
		this.name = name;
		this.imageUrl = imageUrl;
		this.couponCount = couponCount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.couponCoupCategorieses = couponCoupCategorieses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "coupon_count")
	public String getCouponCount() {
		return this.couponCount;
	}

	public void setCouponCount(String couponCount) {
		this.couponCount = couponCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupCategories")
	public Set<CouponCoupCategories> getCouponCoupCategorieses() {
		return this.couponCoupCategorieses;
	}

	public void setCouponCoupCategorieses(Set<CouponCoupCategories> couponCoupCategorieses) {
		this.couponCoupCategorieses = couponCoupCategorieses;
	}

}
