package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CouponCoupCategories generated by hbm2java
 */
@Entity
@Table(name = "coupon_coup_categories", schema = "public")
public class CouponCoupCategories implements java.io.Serializable {

	private long id;
	private CoupCategories coupCategories;
	private Coupons coupons;
	private Date createdAt;
	private Date updatedAt;

	public CouponCoupCategories() {
	}

	public CouponCoupCategories(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public CouponCoupCategories(long id, CoupCategories coupCategories, Coupons coupons, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.coupCategories = coupCategories;
		this.coupons = coupons;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coup_category_id")
	public CoupCategories getCoupCategories() {
		return this.coupCategories;
	}

	public void setCoupCategories(CoupCategories coupCategories) {
		this.coupCategories = coupCategories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id")
	public Coupons getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Coupons coupons) {
		this.coupons = coupons;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
