package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Coupons generated by hbm2java
 */
@Entity
@Table(name = "coupons", schema = "public")
public class Coupons implements java.io.Serializable {

	private long id;
	private Retailers retailers;
	private String title;
	private String couponCode;
	private Date expiryDate;
	private String description;
	private String imageUrl;
	private String discount;
	private Integer discountType;
	private String providerName;
	private Integer couponType;
	private String merchantName;
	private String stepsToRedeem;
	private Date createdAt;
	private Date updatedAt;
	private Integer providerCouponId;
	private Boolean expiryStatus;
	private String affiliateUrl;
	private Long coupCategoryId;
	private Set<CouponCoupCategories> couponCoupCategorieses = new HashSet<CouponCoupCategories>(0);
	private Set<UserCoupons> userCouponses = new HashSet<UserCoupons>(0);

	public Coupons() {
	}

	public Coupons(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Coupons(long id, Retailers retailers, String title, String couponCode, Date expiryDate, String description,
			String imageUrl, String discount, Integer discountType, String providerName, Integer couponType,
			String merchantName, String stepsToRedeem, Date createdAt, Date updatedAt, Integer providerCouponId,
			Boolean expiryStatus, String affiliateUrl, Long coupCategoryId,
			Set<CouponCoupCategories> couponCoupCategorieses, Set<UserCoupons> userCouponses) {
		this.id = id;
		this.retailers = retailers;
		this.title = title;
		this.couponCode = couponCode;
		this.expiryDate = expiryDate;
		this.description = description;
		this.imageUrl = imageUrl;
		this.discount = discount;
		this.discountType = discountType;
		this.providerName = providerName;
		this.couponType = couponType;
		this.merchantName = merchantName;
		this.stepsToRedeem = stepsToRedeem;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.providerCouponId = providerCouponId;
		this.expiryStatus = expiryStatus;
		this.affiliateUrl = affiliateUrl;
		this.coupCategoryId = coupCategoryId;
		this.couponCoupCategorieses = couponCoupCategorieses;
		this.userCouponses = userCouponses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "retailer_id")
	public Retailers getRetailers() {
		return this.retailers;
	}

	public void setRetailers(Retailers retailers) {
		this.retailers = retailers;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "coupon_code")
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", length = 29)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "discount")
	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	@Column(name = "discount_type")
	public Integer getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(Integer discountType) {
		this.discountType = discountType;
	}

	@Column(name = "provider_name")
	public String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	@Column(name = "coupon_type")
	public Integer getCouponType() {
		return this.couponType;
	}

	public void setCouponType(Integer couponType) {
		this.couponType = couponType;
	}

	@Column(name = "merchant_name")
	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	@Column(name = "steps_to_redeem")
	public String getStepsToRedeem() {
		return this.stepsToRedeem;
	}

	public void setStepsToRedeem(String stepsToRedeem) {
		this.stepsToRedeem = stepsToRedeem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "provider_coupon_id")
	public Integer getProviderCouponId() {
		return this.providerCouponId;
	}

	public void setProviderCouponId(Integer providerCouponId) {
		this.providerCouponId = providerCouponId;
	}

	@Column(name = "expiry_status")
	public Boolean getExpiryStatus() {
		return this.expiryStatus;
	}

	public void setExpiryStatus(Boolean expiryStatus) {
		this.expiryStatus = expiryStatus;
	}

	@Column(name = "affiliate_url")
	public String getAffiliateUrl() {
		return this.affiliateUrl;
	}

	public void setAffiliateUrl(String affiliateUrl) {
		this.affiliateUrl = affiliateUrl;
	}

	@Column(name = "coup_category_id")
	public Long getCoupCategoryId() {
		return this.coupCategoryId;
	}

	public void setCoupCategoryId(Long coupCategoryId) {
		this.coupCategoryId = coupCategoryId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupons")
	public Set<CouponCoupCategories> getCouponCoupCategorieses() {
		return this.couponCoupCategorieses;
	}

	public void setCouponCoupCategorieses(Set<CouponCoupCategories> couponCoupCategorieses) {
		this.couponCoupCategorieses = couponCoupCategorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupons")
	public Set<UserCoupons> getUserCouponses() {
		return this.userCouponses;
	}

	public void setUserCouponses(Set<UserCoupons> userCouponses) {
		this.userCouponses = userCouponses;
	}

}
