package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DeliveryTimings generated by hbm2java
 */
@Entity
@Table(name = "delivery_timings", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "shop_id",
		"day" }))
public class DeliveryTimings implements java.io.Serializable {

	private long id;
	private Shops shops;
	private Integer day;
	private Integer startHour;
	private Integer endHour;
	private Date createdAt;
	private Date updatedAt;
	private Boolean halfDay;
	private Integer slotId;

	public DeliveryTimings() {
	}

	public DeliveryTimings(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public DeliveryTimings(long id, Shops shops, Integer day, Integer startHour, Integer endHour, Date createdAt,
			Date updatedAt, Boolean halfDay, Integer slotId) {
		this.id = id;
		this.shops = shops;
		this.day = day;
		this.startHour = startHour;
		this.endHour = endHour;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.halfDay = halfDay;
		this.slotId = slotId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id")
	public Shops getShops() {
		return this.shops;
	}

	public void setShops(Shops shops) {
		this.shops = shops;
	}

	@Column(name = "day")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Column(name = "start_hour")
	public Integer getStartHour() {
		return this.startHour;
	}

	public void setStartHour(Integer startHour) {
		this.startHour = startHour;
	}

	@Column(name = "end_hour")
	public Integer getEndHour() {
		return this.endHour;
	}

	public void setEndHour(Integer endHour) {
		this.endHour = endHour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "half_day")
	public Boolean getHalfDay() {
		return this.halfDay;
	}

	public void setHalfDay(Boolean halfDay) {
		this.halfDay = halfDay;
	}

	@Column(name = "slot_id")
	public Integer getSlotId() {
		return this.slotId;
	}

	public void setSlotId(Integer slotId) {
		this.slotId = slotId;
	}

}
