package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FundTransfers generated by hbm2java
 */
@Entity
@Table(name = "fund_transfers", schema = "public")
public class FundTransfers {

	private long id;
	private UserTransactions userTransactions;
	private Users users;
	private int transactionType;
	private String beneId;
	private String beneName;
	private String benePhoneNumber;
	private String beneAccountNumber;
	private Date createdAt;
	private Date updatedAt;

	public FundTransfers() {
	}

	public FundTransfers(long id, int transactionType, Date createdAt, Date updatedAt) {
		this.id = id;
		this.transactionType = transactionType;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public FundTransfers(long id, UserTransactions userTransactions, Users users, int transactionType, String beneId,
			String beneName, String benePhoneNumber, String beneAccountNumber, Date createdAt, Date updatedAt) {
		this.id = id;
		this.userTransactions = userTransactions;
		this.users = users;
		this.transactionType = transactionType;
		this.beneId = beneId;
		this.beneName = beneName;
		this.benePhoneNumber = benePhoneNumber;
		this.beneAccountNumber = beneAccountNumber;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_transaction_id")
	public UserTransactions getUserTransactions() {
		return this.userTransactions;
	}

	public void setUserTransactions(UserTransactions userTransactions) {
		this.userTransactions = userTransactions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "transaction_type", nullable = false)
	public int getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(int transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "bene_id")
	public String getBeneId() {
		return this.beneId;
	}

	public void setBeneId(String beneId) {
		this.beneId = beneId;
	}

	@Column(name = "bene_name")
	public String getBeneName() {
		return this.beneName;
	}

	public void setBeneName(String beneName) {
		this.beneName = beneName;
	}

	@Column(name = "bene_phone_number")
	public String getBenePhoneNumber() {
		return this.benePhoneNumber;
	}

	public void setBenePhoneNumber(String benePhoneNumber) {
		this.benePhoneNumber = benePhoneNumber;
	}

	@Column(name = "bene_account_number")
	public String getBeneAccountNumber() {
		return this.beneAccountNumber;
	}

	public void setBeneAccountNumber(String beneAccountNumber) {
		this.beneAccountNumber = beneAccountNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
