package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KhataCustomers generated by hbm2java
 */
@Entity
@Table(name = "khata_customers", schema = "public")
public class KhataCustomers implements java.io.Serializable {

	private long id;
	private String name;
	private String phoneNumber;
	private String address;
	private Integer retailerId;
	private Boolean isSync;
	private Date syncTimestamp;
	private Date createdTimestamp;
	private Date modifiedTimestamp;
	private Date createdAt;
	private Date updatedAt;
	private Integer pnbRetailerId;
	private Double closingBalance;

	public KhataCustomers() {
	}

	public KhataCustomers(long id, Date syncTimestamp, Date createdTimestamp, Date modifiedTimestamp, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.syncTimestamp = syncTimestamp;
		this.createdTimestamp = createdTimestamp;
		this.modifiedTimestamp = modifiedTimestamp;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public KhataCustomers(long id, String name, String phoneNumber, String address, Integer retailerId, Boolean isSync,
			Date syncTimestamp, Date createdTimestamp, Date modifiedTimestamp, Date createdAt, Date updatedAt,
			Integer pnbRetailerId, Double closingBalance) {
		this.id = id;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.retailerId = retailerId;
		this.isSync = isSync;
		this.syncTimestamp = syncTimestamp;
		this.createdTimestamp = createdTimestamp;
		this.modifiedTimestamp = modifiedTimestamp;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.pnbRetailerId = pnbRetailerId;
		this.closingBalance = closingBalance;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone_number")
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "retailer_id")
	public Integer getRetailerId() {
		return this.retailerId;
	}

	public void setRetailerId(Integer retailerId) {
		this.retailerId = retailerId;
	}

	@Column(name = "is_sync")
	public Boolean getIsSync() {
		return this.isSync;
	}

	public void setIsSync(Boolean isSync) {
		this.isSync = isSync;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sync_timestamp", nullable = false, length = 29)
	public Date getSyncTimestamp() {
		return this.syncTimestamp;
	}

	public void setSyncTimestamp(Date syncTimestamp) {
		this.syncTimestamp = syncTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_timestamp", nullable = false, length = 29)
	public Date getCreatedTimestamp() {
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_timestamp", nullable = false, length = 29)
	public Date getModifiedTimestamp() {
		return this.modifiedTimestamp;
	}

	public void setModifiedTimestamp(Date modifiedTimestamp) {
		this.modifiedTimestamp = modifiedTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "pnb_retailer_id")
	public Integer getPnbRetailerId() {
		return this.pnbRetailerId;
	}

	public void setPnbRetailerId(Integer pnbRetailerId) {
		this.pnbRetailerId = pnbRetailerId;
	}

	@Column(name = "closing_balance", precision = 17, scale = 17)
	public Double getClosingBalance() {
		return this.closingBalance;
	}

	public void setClosingBalance(Double closingBalance) {
		this.closingBalance = closingBalance;
	}

}
