package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KhataCustomerTransactions generated by hbm2java
 */
@Entity
@Table(name = "khata_customer_transactions", schema = "public")
public class KhataCustomerTransactions implements java.io.Serializable {

	private long id;
	private Integer khataCustomerId;
	private int retailerId;
	private double amount;
	private int txnType;
	private Double closingBalance;
	private int paymentType;
	private String modeRefId;
	private Integer status;
	private Date createdAt;
	private Date updatedAt;
	private Boolean isDeleted;
	private Integer pnbRetailerId;

	public KhataCustomerTransactions() {
	}

	public KhataCustomerTransactions(long id, int retailerId, double amount, int txnType, int paymentType,
			String modeRefId, Date createdAt, Date updatedAt) {
		this.id = id;
		this.retailerId = retailerId;
		this.amount = amount;
		this.txnType = txnType;
		this.paymentType = paymentType;
		this.modeRefId = modeRefId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public KhataCustomerTransactions(long id, Integer khataCustomerId, int retailerId, double amount, int txnType,
			Double closingBalance, int paymentType, String modeRefId, Integer status, Date createdAt, Date updatedAt,
			Boolean isDeleted, Integer pnbRetailerId) {
		this.id = id;
		this.khataCustomerId = khataCustomerId;
		this.retailerId = retailerId;
		this.amount = amount;
		this.txnType = txnType;
		this.closingBalance = closingBalance;
		this.paymentType = paymentType;
		this.modeRefId = modeRefId;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.isDeleted = isDeleted;
		this.pnbRetailerId = pnbRetailerId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "khata_customer_id")
	public Integer getKhataCustomerId() {
		return this.khataCustomerId;
	}

	public void setKhataCustomerId(Integer khataCustomerId) {
		this.khataCustomerId = khataCustomerId;
	}

	@Column(name = "retailer_id", nullable = false)
	public int getRetailerId() {
		return this.retailerId;
	}

	public void setRetailerId(int retailerId) {
		this.retailerId = retailerId;
	}

	@Column(name = "amount", nullable = false, precision = 17, scale = 17)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "txn_type", nullable = false)
	public int getTxnType() {
		return this.txnType;
	}

	public void setTxnType(int txnType) {
		this.txnType = txnType;
	}

	@Column(name = "closing_balance", precision = 17, scale = 17)
	public Double getClosingBalance() {
		return this.closingBalance;
	}

	public void setClosingBalance(Double closingBalance) {
		this.closingBalance = closingBalance;
	}

	@Column(name = "payment_type", nullable = false)
	public int getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(int paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "mode_ref_id", nullable = false)
	public String getModeRefId() {
		return this.modeRefId;
	}

	public void setModeRefId(String modeRefId) {
		this.modeRefId = modeRefId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "pnb_retailer_id")
	public Integer getPnbRetailerId() {
		return this.pnbRetailerId;
	}

	public void setPnbRetailerId(Integer pnbRetailerId) {
		this.pnbRetailerId = pnbRetailerId;
	}

}
