package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoggedExceptions generated by hbm2java
 */
@Entity
@Table(name = "logged_exceptions", schema = "public")
public class LoggedExceptions implements java.io.Serializable {

	private long id;
	private String exceptionClass;
	private String controllerName;
	private String actionName;
	private String message;
	private String backtrace;
	private String environment;
	private String request;
	private Date createdAt;

	public LoggedExceptions() {
	}

	public LoggedExceptions(long id) {
		this.id = id;
	}

	public LoggedExceptions(long id, String exceptionClass, String controllerName, String actionName, String message,
			String backtrace, String environment, String request, Date createdAt) {
		this.id = id;
		this.exceptionClass = exceptionClass;
		this.controllerName = controllerName;
		this.actionName = actionName;
		this.message = message;
		this.backtrace = backtrace;
		this.environment = environment;
		this.request = request;
		this.createdAt = createdAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "exception_class")
	public String getExceptionClass() {
		return this.exceptionClass;
	}

	public void setExceptionClass(String exceptionClass) {
		this.exceptionClass = exceptionClass;
	}

	@Column(name = "controller_name")
	public String getControllerName() {
		return this.controllerName;
	}

	public void setControllerName(String controllerName) {
		this.controllerName = controllerName;
	}

	@Column(name = "action_name")
	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	@Column(name = "message")
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "backtrace")
	public String getBacktrace() {
		return this.backtrace;
	}

	public void setBacktrace(String backtrace) {
		this.backtrace = backtrace;
	}

	@Column(name = "environment")
	public String getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(String environment) {
		this.environment = environment;
	}

	@Column(name = "request")
	public String getRequest() {
		return this.request;
	}

	public void setRequest(String request) {
		this.request = request;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
