package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mdrs generated by hbm2java
 */
@Entity
@Table(name = "mdrs", schema = "public")
public class Mdrs implements java.io.Serializable {

	private long id;
	private Integer paymentMode;
	private Double merchantPermdr;
	private Double merchantFlatmdr;
	private Double pgPermdr;
	private Double pgFlatmdr;
	private Integer minSlab;
	private Integer maxSlab;
	private Integer merchantType;
	private String cardName;
	private Date createdAt;
	private Date updatedAt;
	private Set<OrderCharges> orderChargeses = new HashSet<OrderCharges>(0);

	public Mdrs() {
	}

	public Mdrs(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Mdrs(long id, Integer paymentMode, Double merchantPermdr, Double merchantFlatmdr, Double pgPermdr,
			Double pgFlatmdr, Integer minSlab, Integer maxSlab, Integer merchantType, String cardName, Date createdAt,
			Date updatedAt, Set<OrderCharges> orderChargeses) {
		this.id = id;
		this.paymentMode = paymentMode;
		this.merchantPermdr = merchantPermdr;
		this.merchantFlatmdr = merchantFlatmdr;
		this.pgPermdr = pgPermdr;
		this.pgFlatmdr = pgFlatmdr;
		this.minSlab = minSlab;
		this.maxSlab = maxSlab;
		this.merchantType = merchantType;
		this.cardName = cardName;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderChargeses = orderChargeses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "payment_mode")
	public Integer getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(Integer paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "merchant_permdr", precision = 17, scale = 17)
	public Double getMerchantPermdr() {
		return this.merchantPermdr;
	}

	public void setMerchantPermdr(Double merchantPermdr) {
		this.merchantPermdr = merchantPermdr;
	}

	@Column(name = "merchant_flatmdr", precision = 17, scale = 17)
	public Double getMerchantFlatmdr() {
		return this.merchantFlatmdr;
	}

	public void setMerchantFlatmdr(Double merchantFlatmdr) {
		this.merchantFlatmdr = merchantFlatmdr;
	}

	@Column(name = "pg_permdr", precision = 17, scale = 17)
	public Double getPgPermdr() {
		return this.pgPermdr;
	}

	public void setPgPermdr(Double pgPermdr) {
		this.pgPermdr = pgPermdr;
	}

	@Column(name = "pg_flatmdr", precision = 17, scale = 17)
	public Double getPgFlatmdr() {
		return this.pgFlatmdr;
	}

	public void setPgFlatmdr(Double pgFlatmdr) {
		this.pgFlatmdr = pgFlatmdr;
	}

	@Column(name = "min_slab")
	public Integer getMinSlab() {
		return this.minSlab;
	}

	public void setMinSlab(Integer minSlab) {
		this.minSlab = minSlab;
	}

	@Column(name = "max_slab")
	public Integer getMaxSlab() {
		return this.maxSlab;
	}

	public void setMaxSlab(Integer maxSlab) {
		this.maxSlab = maxSlab;
	}

	@Column(name = "merchant_type")
	public Integer getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(Integer merchantType) {
		this.merchantType = merchantType;
	}

	@Column(name = "card_name")
	public String getCardName() {
		return this.cardName;
	}

	public void setCardName(String cardName) {
		this.cardName = cardName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mdrs")
	public Set<OrderCharges> getOrderChargeses() {
		return this.orderChargeses;
	}

	public void setOrderChargeses(Set<OrderCharges> orderChargeses) {
		this.orderChargeses = orderChargeses;
	}

}
