package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Merchants generated by hbm2java
 */
@Entity
@Table(name = "merchants", schema = "public")
public class Merchants implements java.io.Serializable {

	private long id;
	private String name;
	private String phoneNumber;
	private String passwordDigest;
	private Boolean kycVerified;
	private Boolean bankDetailsVerified;
	private Double walletBalance;
	private String kycRemarks;
	private String bankDetailsRemarks;
	private Date createdAt;
	private Date updatedAt;
	private String email;
	private Set<BankDetails> bankDetailses = new HashSet<BankDetails>(0);
	private Set<UserTransactions> userTransactionses = new HashSet<UserTransactions>(0);

	public Merchants() {
	}

	public Merchants(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Merchants(long id, String name, String phoneNumber, String passwordDigest, Boolean kycVerified,
			Boolean bankDetailsVerified, Double walletBalance, String kycRemarks, String bankDetailsRemarks,
			Date createdAt, Date updatedAt, String email, Set<BankDetails> bankDetailses,
			Set<UserTransactions> userTransactionses) {
		this.id = id;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.passwordDigest = passwordDigest;
		this.kycVerified = kycVerified;
		this.bankDetailsVerified = bankDetailsVerified;
		this.walletBalance = walletBalance;
		this.kycRemarks = kycRemarks;
		this.bankDetailsRemarks = bankDetailsRemarks;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.email = email;
		this.bankDetailses = bankDetailses;
		this.userTransactionses = userTransactionses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone_number")
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "password_digest")
	public String getPasswordDigest() {
		return this.passwordDigest;
	}

	public void setPasswordDigest(String passwordDigest) {
		this.passwordDigest = passwordDigest;
	}

	@Column(name = "kyc_verified")
	public Boolean getKycVerified() {
		return this.kycVerified;
	}

	public void setKycVerified(Boolean kycVerified) {
		this.kycVerified = kycVerified;
	}

	@Column(name = "bank_details_verified")
	public Boolean getBankDetailsVerified() {
		return this.bankDetailsVerified;
	}

	public void setBankDetailsVerified(Boolean bankDetailsVerified) {
		this.bankDetailsVerified = bankDetailsVerified;
	}

	@Column(name = "wallet_balance", precision = 17, scale = 17)
	public Double getWalletBalance() {
		return this.walletBalance;
	}

	public void setWalletBalance(Double walletBalance) {
		this.walletBalance = walletBalance;
	}

	@Column(name = "kyc_remarks")
	public String getKycRemarks() {
		return this.kycRemarks;
	}

	public void setKycRemarks(String kycRemarks) {
		this.kycRemarks = kycRemarks;
	}

	@Column(name = "bank_details_remarks")
	public String getBankDetailsRemarks() {
		return this.bankDetailsRemarks;
	}

	public void setBankDetailsRemarks(String bankDetailsRemarks) {
		this.bankDetailsRemarks = bankDetailsRemarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchants")
	public Set<BankDetails> getBankDetailses() {
		return this.bankDetailses;
	}

	public void setBankDetailses(Set<BankDetails> bankDetailses) {
		this.bankDetailses = bankDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchants")
	public Set<UserTransactions> getUserTransactionses() {
		return this.userTransactionses;
	}

	public void setUserTransactionses(Set<UserTransactions> userTransactionses) {
		this.userTransactionses = userTransactionses;
	}

}
