package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name = "order_items", schema = "public")
public class OrderItems implements java.io.Serializable {

	private long id;
	private Orders orders;
	private Products products;
	private Double amount;
	private Integer quantity;
	private Date createdAt;
	private Date updatedAt;
	private Boolean isDeleted;
	private Boolean isEdited;
	private Boolean isSubstituted;
	private Long productSizeId;
	private Set<OrderItemSubstitutes> orderItemSubstituteses = new HashSet<OrderItemSubstitutes>(0);

	public OrderItems() {
	}

	public OrderItems(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public OrderItems(long id, Orders orders, Products products, Double amount, Integer quantity, Date createdAt,
			Date updatedAt, Boolean isDeleted, Boolean isEdited, Boolean isSubstituted, Long productSizeId,
			Set<OrderItemSubstitutes> orderItemSubstituteses) {
		this.id = id;
		this.orders = orders;
		this.products = products;
		this.amount = amount;
		this.quantity = quantity;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.isDeleted = isDeleted;
		this.isEdited = isEdited;
		this.isSubstituted = isSubstituted;
		this.productSizeId = productSizeId;
		this.orderItemSubstituteses = orderItemSubstituteses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "amount", precision = 17, scale = 17)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "is_edited")
	public Boolean getIsEdited() {
		return this.isEdited;
	}

	public void setIsEdited(Boolean isEdited) {
		this.isEdited = isEdited;
	}

	@Column(name = "is_substituted")
	public Boolean getIsSubstituted() {
		return this.isSubstituted;
	}

	public void setIsSubstituted(Boolean isSubstituted) {
		this.isSubstituted = isSubstituted;
	}

	@Column(name = "product_size_id")
	public Long getProductSizeId() {
		return this.productSizeId;
	}

	public void setProductSizeId(Long productSizeId) {
		this.productSizeId = productSizeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderItems")
	public Set<OrderItemSubstitutes> getOrderItemSubstituteses() {
		return this.orderItemSubstituteses;
	}

	public void setOrderItemSubstituteses(Set<OrderItemSubstitutes> orderItemSubstituteses) {
		this.orderItemSubstituteses = orderItemSubstituteses;
	}

}
