package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderPayments generated by hbm2java
 */
@Entity
@Table(name = "order_payments", schema = "public")
public class OrderPayments implements java.io.Serializable {

	private long id;
	private Orders orders;
	private Double amount;
	private Integer paymentMode;
	private String transactionId;
	private String status;
	private String remark;
	private Integer action;
	private Date createdAt;
	private Date updatedAt;
	private Date paymentStartedAt;
	private Date paymentFinishedAt;
	private Serializable gatewayResponse;

	public OrderPayments() {
	}

	public OrderPayments(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public OrderPayments(long id, Orders orders, Double amount, Integer paymentMode, String transactionId,
			String status, String remark, Integer action, Date createdAt, Date updatedAt, Date paymentStartedAt,
			Date paymentFinishedAt, Serializable gatewayResponse) {
		this.id = id;
		this.orders = orders;
		this.amount = amount;
		this.paymentMode = paymentMode;
		this.transactionId = transactionId;
		this.status = status;
		this.remark = remark;
		this.action = action;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.paymentStartedAt = paymentStartedAt;
		this.paymentFinishedAt = paymentFinishedAt;
		this.gatewayResponse = gatewayResponse;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "amount", precision = 17, scale = 17)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "payment_mode")
	public Integer getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(Integer paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "transaction_id")
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "action")
	public Integer getAction() {
		return this.action;
	}

	public void setAction(Integer action) {
		this.action = action;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_started_at", length = 29)
	public Date getPaymentStartedAt() {
		return this.paymentStartedAt;
	}

	public void setPaymentStartedAt(Date paymentStartedAt) {
		this.paymentStartedAt = paymentStartedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_finished_at", length = 29)
	public Date getPaymentFinishedAt() {
		return this.paymentFinishedAt;
	}

	public void setPaymentFinishedAt(Date paymentFinishedAt) {
		this.paymentFinishedAt = paymentFinishedAt;
	}

	@Column(name = "gateway_response")
	public Serializable getGatewayResponse() {
		return this.gatewayResponse;
	}

	public void setGatewayResponse(Serializable gatewayResponse) {
		this.gatewayResponse = gatewayResponse;
	}

}
