package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderItemSubstitutes generated by hbm2java
 */
@Entity
@Table(name = "order_item_substitutes", schema = "public")
public class OrderItemSubstitutes implements java.io.Serializable {

	private long id;
	private OrderItems orderItems;
	private ProductSizes productSizes;
	private Double amount;
	private Integer quantity;
	private Long productId;
	private Date createdAt;
	private Date updatedAt;
	private Double price;
	private Integer substituteId;
	private Serializable substitutes;

	public OrderItemSubstitutes() {
	}

	public OrderItemSubstitutes(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public OrderItemSubstitutes(long id, OrderItems orderItems, ProductSizes productSizes, Double amount,
			Integer quantity, Long productId, Date createdAt, Date updatedAt, Double price, Integer substituteId,
			Serializable substitutes) {
		this.id = id;
		this.orderItems = orderItems;
		this.productSizes = productSizes;
		this.amount = amount;
		this.quantity = quantity;
		this.productId = productId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.price = price;
		this.substituteId = substituteId;
		this.substitutes = substitutes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_id")
	public OrderItems getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(OrderItems orderItems) {
		this.orderItems = orderItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_size_id")
	public ProductSizes getProductSizes() {
		return this.productSizes;
	}

	public void setProductSizes(ProductSizes productSizes) {
		this.productSizes = productSizes;
	}

	@Column(name = "amount", precision = 17, scale = 17)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "product_id")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "price", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "substitute_id")
	public Integer getSubstituteId() {
		return this.substituteId;
	}

	public void setSubstituteId(Integer substituteId) {
		this.substituteId = substituteId;
	}

	@Column(name = "substitutes")
	public Serializable getSubstitutes() {
		return this.substitutes;
	}

	public void setSubstitutes(Serializable substitutes) {
		this.substitutes = substitutes;
	}

}
