package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductSizes generated by hbm2java
 */
@Entity
@Table(name = "product_sizes", schema = "public")
public class ProductSizes implements java.io.Serializable {

	private long id;
	private Products products;
	private String uom;
	private Double weight;
	private Date createdAt;
	private Date updatedAt;
	private String skuId;
	private Double price;
	private Boolean procured;
	private Boolean isDeleted;
	private String comments;
	private String description;
	private String eanCode;
	private Date deletedAt;
	private Serializable shopCategoryTypeIds;
	private Set<OrderItemSubstitutes> orderItemSubstituteses = new HashSet<OrderItemSubstitutes>(0);

	public ProductSizes() {
	}

	public ProductSizes(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ProductSizes(long id, Products products, String uom, Double weight, Date createdAt, Date updatedAt,
			String skuId, Double price, Boolean procured, Boolean isDeleted, String comments, String description,
			String eanCode, Date deletedAt, Serializable shopCategoryTypeIds,
			Set<OrderItemSubstitutes> orderItemSubstituteses) {
		this.id = id;
		this.products = products;
		this.uom = uom;
		this.weight = weight;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.skuId = skuId;
		this.price = price;
		this.procured = procured;
		this.isDeleted = isDeleted;
		this.comments = comments;
		this.description = description;
		this.eanCode = eanCode;
		this.deletedAt = deletedAt;
		this.shopCategoryTypeIds = shopCategoryTypeIds;
		this.orderItemSubstituteses = orderItemSubstituteses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "uom")
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "weight", precision = 17, scale = 17)
	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "sku_id")
	public String getSkuId() {
		return this.skuId;
	}

	public void setSkuId(String skuId) {
		this.skuId = skuId;
	}

	@Column(name = "price", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "procured")
	public Boolean getProcured() {
		return this.procured;
	}

	public void setProcured(Boolean procured) {
		this.procured = procured;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ean_code")
	public String getEanCode() {
		return this.eanCode;
	}

	public void setEanCode(String eanCode) {
		this.eanCode = eanCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Column(name = "shop_category_type_ids")
	public Serializable getShopCategoryTypeIds() {
		return this.shopCategoryTypeIds;
	}

	public void setShopCategoryTypeIds(Serializable shopCategoryTypeIds) {
		this.shopCategoryTypeIds = shopCategoryTypeIds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productSizes")
	public Set<OrderItemSubstitutes> getOrderItemSubstituteses() {
		return this.orderItemSubstituteses;
	}

	public void setOrderItemSubstituteses(Set<OrderItemSubstitutes> orderItemSubstituteses) {
		this.orderItemSubstituteses = orderItemSubstituteses;
	}

}
