package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reports generated by hbm2java
 */
@Entity
@Table(name = "reports", schema = "public")
public class Reports implements java.io.Serializable {

	private long id;
	private Date date;
	private Serializable cash;
	private Serializable khata;
	private Serializable cnp;
	private Serializable pos;
	private Serializable wallet;
	private Serializable total;
	private Date createdAt;
	private Date updatedAt;
	private Integer retailerId;
	private Serializable metrics;
	private String retailerPhoneNumber;

	public Reports() {
	}

	public Reports(long id, Date date, Date createdAt, Date updatedAt) {
		this.id = id;
		this.date = date;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Reports(long id, Date date, Serializable cash, Serializable khata, Serializable cnp, Serializable pos,
			Serializable wallet, Serializable total, Date createdAt, Date updatedAt, Integer retailerId,
			Serializable metrics, String retailerPhoneNumber) {
		this.id = id;
		this.date = date;
		this.cash = cash;
		this.khata = khata;
		this.cnp = cnp;
		this.pos = pos;
		this.wallet = wallet;
		this.total = total;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.retailerId = retailerId;
		this.metrics = metrics;
		this.retailerPhoneNumber = retailerPhoneNumber;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 13)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "cash")
	public Serializable getCash() {
		return this.cash;
	}

	public void setCash(Serializable cash) {
		this.cash = cash;
	}

	@Column(name = "khata")
	public Serializable getKhata() {
		return this.khata;
	}

	public void setKhata(Serializable khata) {
		this.khata = khata;
	}

	@Column(name = "cnp")
	public Serializable getCnp() {
		return this.cnp;
	}

	public void setCnp(Serializable cnp) {
		this.cnp = cnp;
	}

	@Column(name = "pos")
	public Serializable getPos() {
		return this.pos;
	}

	public void setPos(Serializable pos) {
		this.pos = pos;
	}

	@Column(name = "wallet")
	public Serializable getWallet() {
		return this.wallet;
	}

	public void setWallet(Serializable wallet) {
		this.wallet = wallet;
	}

	@Column(name = "total")
	public Serializable getTotal() {
		return this.total;
	}

	public void setTotal(Serializable total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "retailer_id")
	public Integer getRetailerId() {
		return this.retailerId;
	}

	public void setRetailerId(Integer retailerId) {
		this.retailerId = retailerId;
	}

	@Column(name = "metrics")
	public Serializable getMetrics() {
		return this.metrics;
	}

	public void setMetrics(Serializable metrics) {
		this.metrics = metrics;
	}

	@Column(name = "retailer_phone_number")
	public String getRetailerPhoneNumber() {
		return this.retailerPhoneNumber;
	}

	public void setRetailerPhoneNumber(String retailerPhoneNumber) {
		this.retailerPhoneNumber = retailerPhoneNumber;
	}

}
