package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RetailerPaymentDetails generated by hbm2java
 */
@Entity
@Table(name = "retailer_payment_details", schema = "public")
public class RetailerPaymentDetails implements java.io.Serializable {

	private long id;
	private Shops shops;
	private Boolean cod;
	private Serializable onlinePayment;
	private Serializable bankDetails;
	private Date createdAt;
	private Date updatedAt;

	public RetailerPaymentDetails() {
	}

	public RetailerPaymentDetails(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public RetailerPaymentDetails(long id, Shops shops, Boolean cod, Serializable onlinePayment,
			Serializable bankDetails, Date createdAt, Date updatedAt) {
		this.id = id;
		this.shops = shops;
		this.cod = cod;
		this.onlinePayment = onlinePayment;
		this.bankDetails = bankDetails;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id")
	public Shops getShops() {
		return this.shops;
	}

	public void setShops(Shops shops) {
		this.shops = shops;
	}

	@Column(name = "cod")
	public Boolean getCod() {
		return this.cod;
	}

	public void setCod(Boolean cod) {
		this.cod = cod;
	}

	@Column(name = "online_payment")
	public Serializable getOnlinePayment() {
		return this.onlinePayment;
	}

	public void setOnlinePayment(Serializable onlinePayment) {
		this.onlinePayment = onlinePayment;
	}

	@Column(name = "bank_details")
	public Serializable getBankDetails() {
		return this.bankDetails;
	}

	public void setBankDetails(Serializable bankDetails) {
		this.bankDetails = bankDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
