package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceTaxes generated by hbm2java
 */
@Entity
@Table(name = "service_taxes", schema = "public")
public class ServiceTaxes implements java.io.Serializable {

	private long id;
	private Integer paymentMode;
	private String description;
	private Double serviceTax;
	private Date createdAt;
	private Date updatedAt;
	private Set<OrderCharges> orderChargeses = new HashSet<OrderCharges>(0);

	public ServiceTaxes() {
	}

	public ServiceTaxes(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ServiceTaxes(long id, Integer paymentMode, String description, Double serviceTax, Date createdAt,
			Date updatedAt, Set<OrderCharges> orderChargeses) {
		this.id = id;
		this.paymentMode = paymentMode;
		this.description = description;
		this.serviceTax = serviceTax;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderChargeses = orderChargeses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "payment_mode")
	public Integer getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(Integer paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "service_tax", precision = 17, scale = 17)
	public Double getServiceTax() {
		return this.serviceTax;
	}

	public void setServiceTax(Double serviceTax) {
		this.serviceTax = serviceTax;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceTaxes")
	public Set<OrderCharges> getOrderChargeses() {
		return this.orderChargeses;
	}

	public void setOrderChargeses(Set<OrderCharges> orderChargeses) {
		this.orderChargeses = orderChargeses;
	}

}
