package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shops generated by hbm2java
 */
@Entity
@Table(name = "shops", schema = "public")
public class Shops implements java.io.Serializable {

	private long id;
	private String name;
	private Boolean active;
	private Date createdAt;
	private Date updatedAt;
	private Integer retailerId;
	private Serializable services;
	private String locality;
	private String city;
	private String state;
	private Integer pincode;
	private String placeId;
	private String phoneNumber;
	private String address;
	private Integer deliveryBoysCount;
	private Double deliveryRadius;
	private String img;
	private Double latitude;
	private Double longitude;
	private String location;
	private Boolean foodCategory;
	private Integer shopCategoryId;
	private Integer avgDeliveryTime;
	private String onboardingStatus;
	private Integer cityId;
	private Integer stateId;
	private String comments;
	private Boolean isInventoryBuilt;
	private Serializable subCategoriesSelected;
	private Boolean closedByRetailer;
	private Integer packageId;
	private String shoutOut;
	private Integer modeOfPayment;
	private Integer successfulOrderCount;
	private Serializable images;
	private Integer storeLive;
	private String indexName;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<DeliveryPeople> deliveryPeoples = new HashSet<DeliveryPeople>(0);
	private Set<DeliveryTimings> deliveryTimingses = new HashSet<DeliveryTimings>(0);
	private Set<RetailerPaymentDetails> retailerPaymentDetailses = new HashSet<RetailerPaymentDetails>(0);
	private Set<ShopOrderSpecs> shopOrderSpecses = new HashSet<ShopOrderSpecs>(0);

	public Shops() {
	}

	public Shops(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Shops(long id, String name, Boolean active, Date createdAt, Date updatedAt, Integer retailerId,
			Serializable services, String locality, String city, String state, Integer pincode, String placeId,
			String phoneNumber, String address, Integer deliveryBoysCount, Double deliveryRadius, String img,
			Double latitude, Double longitude, String location, Boolean foodCategory, Integer shopCategoryId,
			Integer avgDeliveryTime, String onboardingStatus, Integer cityId, Integer stateId, String comments,
			Boolean isInventoryBuilt, Serializable subCategoriesSelected, Boolean closedByRetailer, Integer packageId,
			String shoutOut, Integer modeOfPayment, Integer successfulOrderCount, Serializable images,
			Integer storeLive, String indexName, Set<Orders> orderses, Set<DeliveryPeople> deliveryPeoples,
			Set<DeliveryTimings> deliveryTimingses, Set<RetailerPaymentDetails> retailerPaymentDetailses,
			Set<ShopOrderSpecs> shopOrderSpecses) {
		this.id = id;
		this.name = name;
		this.active = active;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.retailerId = retailerId;
		this.services = services;
		this.locality = locality;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
		this.placeId = placeId;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.deliveryBoysCount = deliveryBoysCount;
		this.deliveryRadius = deliveryRadius;
		this.img = img;
		this.latitude = latitude;
		this.longitude = longitude;
		this.location = location;
		this.foodCategory = foodCategory;
		this.shopCategoryId = shopCategoryId;
		this.avgDeliveryTime = avgDeliveryTime;
		this.onboardingStatus = onboardingStatus;
		this.cityId = cityId;
		this.stateId = stateId;
		this.comments = comments;
		this.isInventoryBuilt = isInventoryBuilt;
		this.subCategoriesSelected = subCategoriesSelected;
		this.closedByRetailer = closedByRetailer;
		this.packageId = packageId;
		this.shoutOut = shoutOut;
		this.modeOfPayment = modeOfPayment;
		this.successfulOrderCount = successfulOrderCount;
		this.images = images;
		this.storeLive = storeLive;
		this.indexName = indexName;
		this.orderses = orderses;
		this.deliveryPeoples = deliveryPeoples;
		this.deliveryTimingses = deliveryTimingses;
		this.retailerPaymentDetailses = retailerPaymentDetailses;
		this.shopOrderSpecses = shopOrderSpecses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "retailer_id")
	public Integer getRetailerId() {
		return this.retailerId;
	}

	public void setRetailerId(Integer retailerId) {
		this.retailerId = retailerId;
	}

	@Column(name = "services")
	public Serializable getServices() {
		return this.services;
	}

	public void setServices(Serializable services) {
		this.services = services;
	}

	@Column(name = "locality")
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "pincode")
	public Integer getPincode() {
		return this.pincode;
	}

	public void setPincode(Integer pincode) {
		this.pincode = pincode;
	}

	@Column(name = "place_id")
	public String getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(String placeId) {
		this.placeId = placeId;
	}

	@Column(name = "phone_number")
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "delivery_boys_count")
	public Integer getDeliveryBoysCount() {
		return this.deliveryBoysCount;
	}

	public void setDeliveryBoysCount(Integer deliveryBoysCount) {
		this.deliveryBoysCount = deliveryBoysCount;
	}

	@Column(name = "delivery_radius", precision = 17, scale = 17)
	public Double getDeliveryRadius() {
		return this.deliveryRadius;
	}

	public void setDeliveryRadius(Double deliveryRadius) {
		this.deliveryRadius = deliveryRadius;
	}

	@Column(name = "img")
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "food_category")
	public Boolean getFoodCategory() {
		return this.foodCategory;
	}

	public void setFoodCategory(Boolean foodCategory) {
		this.foodCategory = foodCategory;
	}

	@Column(name = "shop_category_id")
	public Integer getShopCategoryId() {
		return this.shopCategoryId;
	}

	public void setShopCategoryId(Integer shopCategoryId) {
		this.shopCategoryId = shopCategoryId;
	}

	@Column(name = "avg_delivery_time")
	public Integer getAvgDeliveryTime() {
		return this.avgDeliveryTime;
	}

	public void setAvgDeliveryTime(Integer avgDeliveryTime) {
		this.avgDeliveryTime = avgDeliveryTime;
	}

	@Column(name = "onboarding_status")
	public String getOnboardingStatus() {
		return this.onboardingStatus;
	}

	public void setOnboardingStatus(String onboardingStatus) {
		this.onboardingStatus = onboardingStatus;
	}

	@Column(name = "city_id")
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "state_id")
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "is_inventory_built")
	public Boolean getIsInventoryBuilt() {
		return this.isInventoryBuilt;
	}

	public void setIsInventoryBuilt(Boolean isInventoryBuilt) {
		this.isInventoryBuilt = isInventoryBuilt;
	}

	@Column(name = "sub_categories_selected")
	public Serializable getSubCategoriesSelected() {
		return this.subCategoriesSelected;
	}

	public void setSubCategoriesSelected(Serializable subCategoriesSelected) {
		this.subCategoriesSelected = subCategoriesSelected;
	}

	@Column(name = "closed_by_retailer")
	public Boolean getClosedByRetailer() {
		return this.closedByRetailer;
	}

	public void setClosedByRetailer(Boolean closedByRetailer) {
		this.closedByRetailer = closedByRetailer;
	}

	@Column(name = "package_id")
	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	@Column(name = "shout_out")
	public String getShoutOut() {
		return this.shoutOut;
	}

	public void setShoutOut(String shoutOut) {
		this.shoutOut = shoutOut;
	}

	@Column(name = "mode_of_payment")
	public Integer getModeOfPayment() {
		return this.modeOfPayment;
	}

	public void setModeOfPayment(Integer modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}

	@Column(name = "successful_order_count")
	public Integer getSuccessfulOrderCount() {
		return this.successfulOrderCount;
	}

	public void setSuccessfulOrderCount(Integer successfulOrderCount) {
		this.successfulOrderCount = successfulOrderCount;
	}

	@Column(name = "images")
	public Serializable getImages() {
		return this.images;
	}

	public void setImages(Serializable images) {
		this.images = images;
	}

	@Column(name = "store_live")
	public Integer getStoreLive() {
		return this.storeLive;
	}

	public void setStoreLive(Integer storeLive) {
		this.storeLive = storeLive;
	}

	@Column(name = "index_name")
	public String getIndexName() {
		return this.indexName;
	}

	public void setIndexName(String indexName) {
		this.indexName = indexName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shops")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shops")
	public Set<DeliveryPeople> getDeliveryPeoples() {
		return this.deliveryPeoples;
	}

	public void setDeliveryPeoples(Set<DeliveryPeople> deliveryPeoples) {
		this.deliveryPeoples = deliveryPeoples;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shops")
	public Set<DeliveryTimings> getDeliveryTimingses() {
		return this.deliveryTimingses;
	}

	public void setDeliveryTimingses(Set<DeliveryTimings> deliveryTimingses) {
		this.deliveryTimingses = deliveryTimingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shops")
	public Set<RetailerPaymentDetails> getRetailerPaymentDetailses() {
		return this.retailerPaymentDetailses;
	}

	public void setRetailerPaymentDetailses(Set<RetailerPaymentDetails> retailerPaymentDetailses) {
		this.retailerPaymentDetailses = retailerPaymentDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shops")
	public Set<ShopOrderSpecs> getShopOrderSpecses() {
		return this.shopOrderSpecses;
	}

	public void setShopOrderSpecses(Set<ShopOrderSpecs> shopOrderSpecses) {
		this.shopOrderSpecses = shopOrderSpecses;
	}

}
