package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubCategories generated by hbm2java
 */
@Entity
@Table(name = "sub_categories", schema = "public")
public class SubCategories implements java.io.Serializable {

	private long id;
	private Categories categories;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private String image;
	private Serializable alternateNames;
	private Set<BrandsSubCategories> brandsSubCategorieses = new HashSet<BrandsSubCategories>(0);
	private Set<Products> productses = new HashSet<Products>(0);

	public SubCategories() {
	}

	public SubCategories(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public SubCategories(long id, Categories categories, String name, Date createdAt, Date updatedAt, String image,
			Serializable alternateNames, Set<BrandsSubCategories> brandsSubCategorieses, Set<Products> productses) {
		this.id = id;
		this.categories = categories;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.image = image;
		this.alternateNames = alternateNames;
		this.brandsSubCategorieses = brandsSubCategorieses;
		this.productses = productses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "alternate_names")
	public Serializable getAlternateNames() {
		return this.alternateNames;
	}

	public void setAlternateNames(Serializable alternateNames) {
		this.alternateNames = alternateNames;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subCategories")
	public Set<BrandsSubCategories> getBrandsSubCategorieses() {
		return this.brandsSubCategorieses;
	}

	public void setBrandsSubCategorieses(Set<BrandsSubCategories> brandsSubCategorieses) {
		this.brandsSubCategorieses = brandsSubCategorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subCategories")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
