package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDeliveryAddresses generated by hbm2java
 */
@Entity
@Table(name = "user_delivery_addresses", schema = "public")
public class UserDeliveryAddresses implements java.io.Serializable {

	private long id;
	private Integer userId;
	private Date createdAt;
	private Date updatedAt;
	private String city;
	private String state;
	private String pincode;
	private String addressType;
	private Double latitude;
	private Double longitude;
	private String societyName;
	private String flatNo;
	private String building;
	private String streetAndLocality;
	private Integer societyId;
	private Boolean isSociety;
	private String firstLine;
	private String landmark;
	private Date deletedAt;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public UserDeliveryAddresses() {
	}

	public UserDeliveryAddresses(long id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public UserDeliveryAddresses(long id, Integer userId, Date createdAt, Date updatedAt, String city, String state,
			String pincode, String addressType, Double latitude, Double longitude, String societyName, String flatNo,
			String building, String streetAndLocality, Integer societyId, Boolean isSociety, String firstLine,
			String landmark, Date deletedAt, Set<Orders> orderses) {
		this.id = id;
		this.userId = userId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
		this.addressType = addressType;
		this.latitude = latitude;
		this.longitude = longitude;
		this.societyName = societyName;
		this.flatNo = flatNo;
		this.building = building;
		this.streetAndLocality = streetAndLocality;
		this.societyId = societyId;
		this.isSociety = isSociety;
		this.firstLine = firstLine;
		this.landmark = landmark;
		this.deletedAt = deletedAt;
		this.orderses = orderses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "pincode")
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "address_type")
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "society_name")
	public String getSocietyName() {
		return this.societyName;
	}

	public void setSocietyName(String societyName) {
		this.societyName = societyName;
	}

	@Column(name = "flat_no")
	public String getFlatNo() {
		return this.flatNo;
	}

	public void setFlatNo(String flatNo) {
		this.flatNo = flatNo;
	}

	@Column(name = "building")
	public String getBuilding() {
		return this.building;
	}

	public void setBuilding(String building) {
		this.building = building;
	}

	@Column(name = "street_and_locality")
	public String getStreetAndLocality() {
		return this.streetAndLocality;
	}

	public void setStreetAndLocality(String streetAndLocality) {
		this.streetAndLocality = streetAndLocality;
	}

	@Column(name = "society_id")
	public Integer getSocietyId() {
		return this.societyId;
	}

	public void setSocietyId(Integer societyId) {
		this.societyId = societyId;
	}

	@Column(name = "is_society")
	public Boolean getIsSociety() {
		return this.isSociety;
	}

	public void setIsSociety(Boolean isSociety) {
		this.isSociety = isSociety;
	}

	@Column(name = "first_line")
	public String getFirstLine() {
		return this.firstLine;
	}

	public void setFirstLine(String firstLine) {
		this.firstLine = firstLine;
	}

	@Column(name = "landmark")
	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDeliveryAddresses")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
