package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Versions generated by hbm2java
 */
@Entity
@Table(name = "versions", schema = "public")
public class Versions implements java.io.Serializable {

	private long id;
	private String itemType;
	private int itemId;
	private String event;
	private String whodunnit;
	private String object;
	private Date createdAt;
	private String objectChanges;
	private Integer transactionId;

	public Versions() {
	}

	public Versions(long id, String itemType, int itemId, String event) {
		this.id = id;
		this.itemType = itemType;
		this.itemId = itemId;
		this.event = event;
	}

	public Versions(long id, String itemType, int itemId, String event, String whodunnit, String object, Date createdAt,
			String objectChanges, Integer transactionId) {
		this.id = id;
		this.itemType = itemType;
		this.itemId = itemId;
		this.event = event;
		this.whodunnit = whodunnit;
		this.object = object;
		this.createdAt = createdAt;
		this.objectChanges = objectChanges;
		this.transactionId = transactionId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "item_type", nullable = false)
	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	@Column(name = "item_id", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "event", nullable = false)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "whodunnit")
	public String getWhodunnit() {
		return this.whodunnit;
	}

	public void setWhodunnit(String whodunnit) {
		this.whodunnit = whodunnit;
	}

	@Column(name = "object")
	public String getObject() {
		return this.object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "object_changes")
	public String getObjectChanges() {
		return this.objectChanges;
	}

	public void setObjectChanges(String objectChanges) {
		this.objectChanges = objectChanges;
	}

	@Column(name = "transaction_id")
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

}
