package com.bnb.model;
// Generated 30 Jul, 2020 3:44:28 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VersionAssociations generated by hbm2java
 */
@Entity
@Table(name = "version_associations", schema = "public")
public class VersionAssociations implements java.io.Serializable {

	private long id;
	private Integer versionId;
	private String foreignKeyName;
	private Integer foreignKeyId;

	public VersionAssociations() {
	}

	public VersionAssociations(long id, String foreignKeyName) {
		this.id = id;
		this.foreignKeyName = foreignKeyName;
	}

	public VersionAssociations(long id, Integer versionId, String foreignKeyName, Integer foreignKeyId) {
		this.id = id;
		this.versionId = versionId;
		this.foreignKeyName = foreignKeyName;
		this.foreignKeyId = foreignKeyId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "version_id")
	public Integer getVersionId() {
		return this.versionId;
	}

	public void setVersionId(Integer versionId) {
		this.versionId = versionId;
	}

	@Column(name = "foreign_key_name", nullable = false)
	public String getForeignKeyName() {
		return this.foreignKeyName;
	}

	public void setForeignKeyName(String foreignKeyName) {
		this.foreignKeyName = foreignKeyName;
	}

	@Column(name = "foreign_key_id")
	public Integer getForeignKeyId() {
		return this.foreignKeyId;
	}

	public void setForeignKeyId(Integer foreignKeyId) {
		this.foreignKeyId = foreignKeyId;
	}

}
